name: chinese_lunar_calendar
description: A Dart Package for creating Chinese Lunar Calendar. It runs locally and doesn't depend on any remote API. 中国万年历查询, 本地运行，不依赖远程API。
version: 0.0.2
homepage: https://github.com/m11v/chinese_lunar_calendar
repository: https://github.com/m11v/chinese_lunar_calendar

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
